[package]
name = "aoc_2019"
version = "0.1.0"
authors = ["Stephen Bennett <bennett18@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
bench = false

[dependencies]
aoc-runner = "*"
aoc-runner-derive = "*"
regex = "1"
